/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author skypper
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeView = new views.HomeView();
        menuBar = new javax.swing.JMenuBar();
        sesionMenu = new javax.swing.JMenu();
        loginMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        lineasMenu = new javax.swing.JMenu();
        createLineaMenuItem = new javax.swing.JMenuItem();
        listLineaMenuItem = new javax.swing.JMenuItem();
        rutasMenu = new javax.swing.JMenu();
        listParadaMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sesionMenu.setText("Sesión");

        loginMenuItem.setText("Iniciar Sesión");
        sesionMenu.add(loginMenuItem);

        logoutMenuItem.setText("Cerrar Sesión");
        sesionMenu.add(logoutMenuItem);

        menuBar.add(sesionMenu);

        lineasMenu.setText("Lineas");

        createLineaMenuItem.setText("Crear Lineas");
        lineasMenu.add(createLineaMenuItem);

        listLineaMenuItem.setText("Ver Lineas");
        lineasMenu.add(listLineaMenuItem);

        menuBar.add(lineasMenu);

        rutasMenu.setText("Rutas");

        listParadaMenuItem.setText("Ver Paradas");
        rutasMenu.add(listParadaMenuItem);

        menuBar.add(rutasMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem createLineaMenuItem;
    private views.HomeView homeView;
    public javax.swing.JMenu lineasMenu;
    public javax.swing.JMenuItem listLineaMenuItem;
    public javax.swing.JMenuItem listParadaMenuItem;
    public javax.swing.JMenuItem loginMenuItem;
    public javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuBar menuBar;
    public javax.swing.JMenu rutasMenu;
    public javax.swing.JMenu sesionMenu;
    // End of variables declaration//GEN-END:variables
}
